# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)/WebApp-ASP.Net core/terraform-manifests'
    projectName: 'terraform-project'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'



- task: AzureFileCopy@6
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/WebApp-ASP.Net core/*'
    azureSubscription: 'Dev Test (18a0e420-4ca6-47f3-ba52-2534b3c7d2c1)'
    Destination: 'AzureBlob'
    storage: 'storagedevopspulse01'
    ContainerName: 'container01'
    BlobPrefix: 'artifacts/'
